// Katelyn Holt
// Generated to test ADD A COURSE form and associated files
// Recycled code from AllStudentsForm generated by Rick Decker
// CISS 311, Advanced Agile, C# Champions Final Project, Project 1

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ProjectOne
{
    public partial class AllCoursesForm : Form
    {
        public AllCoursesForm()
        {
            InitializeComponent();
        }

        private void CloseButton_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void AllCoursesForm_Load(object sender, EventArgs e)
        {
            try
            {
                // Clear existing items in case this event fires multiple times
                AllCourseslistBox.Items.Clear();

                // Call the GetAllStudents method from your DatabaseManager
                var courses = new DatabaseManager().GetAllCourses();
                                
                // Add students to the ListBox
                foreach (var course in courses)
                {                    
                    /* Old Display All Courses format, displaying each 
                     * attribute of a Course in a new line
                     * AllCourseslistBox.Items.Add(course.CourseID);
                     * AllCourseslistBox.Items.Add(course.CourseTitle);                    
                     * AllCourseslistBox.Items.Add(course.SemesterOffered);
                     */

                    // Format the course as a string and add it to the ListBox.                   
                    AllCourseslistBox.Items.Add($"{course.CourseID} - {course.CourseTitle} ({course.SemesterOffered})");

                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error populating courses: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
